# This python will be used to track my .py projects.

print()
print("Week 0:")
print("List of projects:")
print("1.py: Simple conversation")
print("2.py: Simple conversation") 
print("3.py: Simple 2-constant calculator")
print("4.py: Replayable 2-constant calculator")
print("5.py: Assignment Time Estimator")
print("6.py: Tip Calculator")
print("7.py: Calculator using return")
print("8.py: ")
print("9.py: ")
print("10.py: ")
print("11.py: ")

print()
print("Week 1:")
print("12.py: ")