# This python will be used to track my .py projects.

print()
print("Week 0:")
print("List of projects:")
print("1. Simple conversation")
print("2. Simple conversation") 
print("3. Simple 2-constant calculator")
print("4. Replayable 2-constant calculator")
print("5. Assignment Time Estimator")
print("6. Tip Calculator")
print("7. Calculator using return")
print("8. Simple Structured Calculator")
print("9. Text Inside Voice Converter")
print("10. Word Counter")
print("11. Mixed Problem Set")

print()
print("Week 1:")
print("12. Odd or Even Checker")
print("13. Empowerment Technologies 10-item Quiz")
print("14. Color Sorter")
print("15. Game Recommender")
print("16. The Hitchhiker's Digital Cafe")

print()
print("Week 2:")
print("17. Calculator or Match")
print("18. Fruit")