# This python will be used to track my .py projects.

print()
print("Week 0:")
print("List of projects:")
print("1. Simple conversation")
print("2. Simple conversation") 
print("3. Simple 2-constant calculator")
print("4. Replayable 2-constant calculator")
print("5. Assignment Time Estimator")
print("6. Tip Calculator")
print("7. Calculator using return")
print("8. Simple Structured Calculator")
print("9. Text Inside Voice Converter")
print("10. Word Counter")
print("11. Mixed Problem Set")

print()
print("Week 1:")
print("12. Odd or Even Checker")
print("13. Retakable 10-item Quiz")
print("14. ")
print("15. ")
print("16. ")